window.REGISTRY_DATA = [
  {
    "Country": "Poland",
    "Area of check": "Corporate verification",
    "Source type": "Public register",
    "Register / Portal": "KRS Search",
    "Authority": "Ministry of Justice",
    "What to verify": "Company name, KRS number, NIP, REGON, legal form, registered address, representatives, company status",
    "Search by": "KRS \nNIP\ncompany name",
    "Link": "https://wyszukiwarka-krs.ms.gov.pl/",
    "Notes": "Used to verify corporate registration data"
  },
  {
    "Country": "Poland",
    "Area of check": "Business activity verification",
    "Source type": "Public statistical database",
    "Register / Portal": "Baza Internetowa REGON (BIR)",
    "Authority": "Statistics Poland / GUS",
    "What to verify": "Main and additional PKD activity codes, REGON number, company name, registered address, legal form and business activity status",
    "Search by": "REGON\nNIP\nKRS",
    "Link": "https://wyszukiwarkaregon.stat.gov.pl/appBIR/index.aspx",
    "Notes": "Used to verify the company’s declared business activity profile and statistical registration data"
  },
  {
    "Country": "Poland",
    "Area of check": "Financial documents verification",
    "Source type": "Public register / financial documents repository",
    "Register / Portal": "Repository of Financial Documents / RDF",
    "Authority": "Ministry of Justice  (KRS)",
    "What to verify": "Annual financial statements, balance sheet, profit and loss statement, auditor’s report if applicable, approval resolutions, management report, consolidated financial statements where applicable",
    "Search by": "KRS number",
    "Link": "https://rdf-przegladarka.ms.gov.pl/wyszukaj-podmiot",
    "Notes": "Used to obtain filed financial documents and verify the availability of official financial reporting submitted by the company"
  },
  {
    "Country": "Poland",
    "Area of check": "UBO verification",
    "Source type": "Public register",
    "Register / Portal": "CRBR",
    "Authority": "Ministry of Finance",
    "What to verify": "Beneficial owners, citizenship, residence country, PESEL/date of birth, ownership share",
    "Search by": "NIP\nKRS",
    "Link": "https://crbr.podatki.gov.pl/adcrbr/#/wyszukaj",
    "Notes": "Used for UBO identification and ownership verification"
  },
  {
    "Country": "Poland",
    "Area of check": "Sanctions screening Poland",
    "Source type": "Sanctions list",
    "Register / Portal": "Polish sanctions list / Lista osób i podmiotów objętych sankcjami",
    "Authority": "Ministry of Interior and Administration",
    "What to verify": "Sanctioned individuals and entities, identification details, grounds for listing, restrictive measures applied, date of listing and date of removal, where applicable",
    "Search by": "Full name\nKRS\nNIP",
    "Link": "https://www.gov.pl/web/mswia/lista-osob-i-podmiotow-objetych-sankcjami",
    "Notes": "Used to screen the company, UBOs, directors, representatives and other related parties against the Polish sanctions list"
  },
  {
    "Country": "Poland",
    "Area of check": "Insolvency and debt check",
    "Source type": "Public register",
    "Register / Portal": "National Register of Debtors / KRZ",
    "Authority": "Ministry of Justice",
    "What to verify": "Bankruptcy, restructuring proceedings, business activity bans, ineffective enforcement proceedings or debt-related records involving individuals",
    "Search by": "Company name\nKRS\nNIP\nfull name\nPESEL",
    "Link": "https://krz.ms.gov.pl/#!/application/KRZPortalPUB/1.9/KrzRejPubGui.WyszukiwaniePodmiotow?params=JTdCJTdE&seq=0",
    "Notes": "Used to identify insolvency, debt or enforcement-related risks"
  },
  {
    "Country": "Poland",
    "Area of check": "Company court and adverse litigation check",
    "Source type": "Court register",
    "Register / Portal": "Portal of Common Court Judgments",
    "Authority": "Ministry of Justice",
    "What to verify": "Published court judgments, disputes, fraud-related cases, unfair practice indicators or other adverse litigation involving the company",
    "Search by": "Company name\nKRS\nNIP\nPolish keywords",
    "Link": "https://orzeczenia.ms.gov.pl/",
    "Notes": "Used to identify adverse litigation, disputes or reputational risks involving the company"
  },
  {
    "Country": "Poland",
    "Area of check": "VASP registration verification",
    "Source type": "Regulatory register",
    "Register / Portal": "Register of Virtual Currency Activities / Rejestr działalności w zakresie walut wirtualnych",
    "Authority": "Director of the Tax Administration Chamber in Katowice",
    "What to verify": "Registration number, company name, NIP, KRS number, type of virtual currency activity, date of entry, suspension or termination of activity",
    "Search by": "Company name\nNIP\nKRS\nRDWW number",
    "Link": "https://www.gov.pl/web/ias-katowice/rejestr-dzialalnosci-w-zakresie-walut-wirtualnych",
    "Notes": "Used to verify whether the entity is entered in the Polish register for virtual currency activities"
  },
  {
    "Country": "Poland",
    "Area of check": "Small Payment Institution registration verification / MIP",
    "Source type": "Regulatory register",
    "Register / Portal": "KNF e-RUP / Register of Payment Service Providers",
    "Authority": "Polish Financial Supervision Authority / KNF",
    "What to verify": "Registration status, registration number, company name, scope of payment services, date of entry, agents and branches, where applicable",
    "Search by": "Company name\nregistration number",
    "Link": "https://e-rup.knf.gov.pl/",
    "Notes": "Used to verify whether the entity is registered with KNF as a Small Payment Institution in Poland"
  },
  {
    "Country": "Poland",
    "Area of check": "Company regulatory warning check",
    "Source type": "Warning list",
    "Register / Portal": "KNF Public Warnings List",
    "Authority": "Polish Financial Supervision Authority / KNF",
    "What to verify": "Subject name, legal basis, qualification of alleged breach, case status, indictment, discontinuation or final court decision, where available",
    "Search by": "Company name\nKRS\nNIP",
    "Link": "https://www.knf.gov.pl/dla_konsumenta/ostrzezenia_publiczne",
    "Notes": "Used to identify KNF public warnings or regulatory concerns involving the company"
  },
  {
    "Country": "Lithuania",
    "Area of check": "Corporate verification",
    "Source type": "Public register / open data",
    "Register / Portal": "Register of Legal Entities / Juridinių asmenų registras",
    "Authority": "State Enterprise Centre of Registers / Registrų centras",
    "What to verify": "Company name, legal entity code, registration date, legal form, registered address and company status",
    "Search by": "Company name\nlegal entity code",
    "Link": "https://www.registrucentras.lt/atviri-duomenys-ir-statistika/jar-pirminiai-duomenys-raw-data",
    "Notes": "Used to verify official corporate registration data. The data is usually downloaded as a file and searched by company name or legal entity code"
  },
  {
    "Country": "Lithuania",
    "Area of check": "Corporate verification",
    "Source type": "Business database / company directory",
    "Register / Portal": "Rekvizitai.lt",
    "Authority": "Rekvizitai.lt",
    "What to verify": "Company name, legal address, director’s name, contact details and general company profile information",
    "Search by": "Company name\nlegal entity code",
    "Link": "https://rekvizitai.vz.lt/ru/",
    "Notes": "Used as a supplementary source to cross-check company profile details and director information"
  },
  {
    "Country": "Lithuania",
    "Area of check": "Corporate verification",
    "Source type": "Commercial database / aggregated register data",
    "Register / Portal": "Lursoft IT",
    "Authority": "Lursoft",
    "What to verify": "Company name, legal form, registration code, registration date, status, address, share capital, VAT data, business activity code and officers, where available",
    "Search by": "Company name\nregistration number",
    "Link": "https://www.lursoft.lv/?l=ru",
    "Notes": "Used as an additional source to cross-check corporate data, company status, activity profile and available officer information"
  },
  {
    "Country": "Lithuania",
    "Area of check": "Sanctions  screening Lithuania",
    "Source type": "Sanctions-related list",
    "Register / Portal": "FNTT list of sanctioned subjects",
    "Authority": "Financial Crime Investigation Service / FNTT",
    "What to verify": "Legal entities or organisations owned or controlled by sanctioned persons or sanctioned entities",
    "Search by": "Company name\nrelated party name",
    "Link": "https://fntt.lrv.lt/en/international-financial-sanctions/a-list-of-sanctioned-subjects/",
    "Notes": "Used to identify whether the company or related entities are linked to sanctioned subjects"
  },
  {
    "Country": "Lithuania",
    "Area of check": "Regulatory adverse media / financial crime check",
    "Source type": "Regulatory press releases",
    "Register / Portal": "FNTT Press Releases",
    "Authority": "Financial Crime Investigation Service / FNTT",
    "What to verify": "AML, fraud, financial crime, sanctions-related or other adverse mentions in FNTT publications",
    "Search by": "Company name\nfull name\nkeywords",
    "Link": "https://fntt.lrv.lt/en/press-releases/?q=&publication_at=&pv=12",
    "Notes": "Used to identify adverse regulatory or financial crime-related information involving the company, UBOs, directors or representatives"
  },
  {
    "Country": "Lithuania",
    "Area of check": "Financial services licence verification",
    "Source type": "Regulatory register",
    "Register / Portal": "Bank of Lithuania Licences",
    "Authority": "Bank of Lithuania",
    "What to verify": "Licence or authorisation status, licence type, financial market participant details and permitted regulated activity",
    "Search by": "Company name\nlicence number\nlicence type",
    "Link": "https://www.lb.lt/lt/licencijos",
    "Notes": "Used to verify whether the entity is licensed or authorised by the Bank of Lithuania as a financial market participant"
  },
  {
    "Country": "Lithuania",
    "Area of check": "CASP / crypto-asset service provider licence verification",
    "Source type": "Regulatory register",
    "Register / Portal": "Bank of Lithuania FRD Licences / Crypto-asset service provider licences",
    "Authority": "Bank of Lithuania",
    "What to verify": "Licence or authorisation status for crypto-asset services, licence type, entity name and scope of regulated activity",
    "Search by": "Company name\nlicence number\nlicence type",
    "Link": "https://www.lb.lt/lt/frd-licencijos?ff=1&type=119",
    "Notes": "Used to verify whether the entity is licensed or authorised to provide crypto-asset services in Lithuania"
  },
  {
    "Country": "Lithuania",
    "Area of check": "Licence data request / additional licence verification",
    "Source type": "Licence information system / data request service",
    "Register / Portal": "Licensing Information System / LIS",
    "Authority": "State Enterprise Centre of Registers / Registrų centras",
    "What to verify": "Licence data held in the Licensing Information System for a legal or natural person",
    "Search by": "Company name\nlegal entity code\nrequest by email",
    "Link": "https://www.registrucentras.lt/lt/paslauga/c25b1a91-08bd-484c-a378-8f2f45a61af6",
    "Notes": "Used as an additional request-based source where licence information needs to be obtained from the Licensing Information System"
  },
  {
    "Country": "United Kingdom",
    "Area of check": "Corporate verification",
    "Source type": "Public register",
    "Register / Portal": "Companies House",
    "Authority": "Companies House",
    "What to verify": "Company name, company number, registered address, company status, legal form, incorporation date, SIC codes, officers, persons with significant control, filing history, accounts and charges",
    "Search by": "Company name\ncompany number",
    "Link": "https://www.gov.uk/government/organisations/companies-house",
    "Notes": "Used to verify official corporate registration data, company status, officers and ownership-related information"
  },
  {
    "Country": "United Kingdom",
    "Area of check": "Financial services authorisation verification",
    "Source type": "Regulatory register",
    "Register / Portal": "Financial Services Register",
    "Authority": "Financial Conduct Authority / FCA",
    "What to verify": "FCA authorisation status, firm reference number, regulated activities, permissions, restrictions, appointed representatives and current regulatory status",
    "Search by": "Company name\nFRN\npostcode",
    "Link": "https://register.fca.org.uk/s/firm",
    "Notes": "Used to verify whether the entity is authorised or registered by the FCA and to confirm the scope of permitted regulated activities"
  },
  {
    "Country": "United Kingdom",
    "Area of check": "FCA firm status check",
    "Source type": "Regulatory checker",
    "Register / Portal": "FCA Firm Checker",
    "Authority": "Financial Conduct Authority / FCA",
    "What to verify": "Firm status, whether the firm is authorised, registered or potentially unauthorised, and whether consumers are protected when dealing with the firm",
    "Search by": "Company name\nFRN\nwebsite\ncontact details",
    "Link": "https://www.fca.org.uk/consumers/fca-firm-checker/search",
    "Notes": "Used as an additional FCA check to confirm the firm’s regulatory status and identify potential warning indicators"
  },
  {
    "Country": "United Kingdom",
    "Area of check": "Regulatory warning check",
    "Source type": "Warning list",
    "Register / Portal": "FCA Warning List of Unauthorised Firms",
    "Authority": "Financial Conduct Authority / FCA",
    "What to verify": "Unauthorised firms, clone firms, warning notices, firm names, websites, contact details and warning reasons",
    "Search by": "Company name\nwebsite\nphone number\nemail",
    "Link": "https://www.fca.org.uk/consumers/warning-list-unauthorised-firms",
    "Notes": "Used to identify FCA warnings, unauthorised activity or clone-firm risk involving the company"
  },
  {
    "Country": "United Kingdom",
    "Area of check": "Customer complaints / ombudsman check",
    "Source type": "Ombudsman decisions database",
    "Register / Portal": "Financial Ombudsman Service",
    "Authority": "Financial Ombudsman Service / FOS",
    "What to verify": "Complaints, ombudsman decisions, upheld complaints and customer dispute history involving financial service providers",
    "Search by": "Company name\ntrading name\nkeywords",
    "Link": "https://www.financial-ombudsman.org.uk/",
    "Notes": "Used to identify customer complaints, dispute history and conduct-related risk indicators"
  },
  {
    "Country": "United Kingdom",
    "Area of check": "Court and adverse litigation check",
    "Source type": "Court decisions database",
    "Register / Portal": "Find Case Law",
    "Authority": "The National Archives",
    "What to verify": "Published court and tribunal decisions, civil disputes, enforcement, fraud-related cases, insolvency-related litigation or other adverse litigation",
    "Search by": "Company name\nindividual name\nkeywords",
    "Link": "https://caselaw.nationalarchives.gov.uk/",
    "Notes": "Used to identify adverse litigation, disputes or reputational risks involving the company, UBOs, directors or representatives"
  },
  {
    "Country": "United Kingdom",
    "Area of check": "Insolvency and bankruptcy check",
    "Source type": "Public insolvency register",
    "Register / Portal": "Individual Insolvency Register",
    "Authority": "Insolvency Service",
    "What to verify": "Bankruptcy orders, debt relief orders, individual voluntary arrangements and insolvency status of individuals",
    "Search by": "full name\ntrading name",
    "Link": "https://www.insolvencydirect.bis.gov.uk/eiir/",
    "Notes": "Used to identify insolvency or bankruptcy-related risks involving directors, UBOs, representatives or sole traders"
  },
  {
    "Country": "Switzerland",
    "Area of check": "Corporate verification",
    "Source type": "Public register",
    "Register / Portal": "ZEFIX / Central Business Name Index",
    "Authority": "Federal Commercial Registry Office",
    "What to verify": "Company name, legal form, registered address, company status, UID/registration number, purpose of activity and registered persons",
    "Search by": "Company name / UID / registration number",
    "Link": "https://www.zefix.admin.ch/de/search/entity/welcome",
    "Notes": "Used to verify official corporate registration data and persons registered with authority to represent the company"
  },
  {
    "Country": "Switzerland",
    "Area of check": "Corporate verification",
    "Source type": "Public register",
    "Register / Portal": "Cantonal Commercial Registers / Handelsregisterämter",
    "Authority": "Cantonal Commercial Registry Offices",
    "What to verify": "Published company data, legal form, purpose of activity, registered address and registered persons",
    "Search by": "Company name / UID / registration number",
    "Link": "https://www.zefix.ch/en/hra",
    "Notes": "Used as an additional source to access cantonal commercial register information and official extracts where applicable"
  },
  {
    "Country": "Switzerland",
    "Area of check": "SRO membership verification",
    "Source type": "Regulatory / SRO register",
    "Register / Portal": "FINMA SRO Member Search",
    "Authority": "Swiss Financial Market Supervisory Authority / FINMA",
    "What to verify": "Whether the entity is affiliated with a recognised self-regulatory organisation, SRO name and membership-related information where available",
    "Search by": "Company name",
    "Link": "https://www.finma.ch/en/authorisation/self-regulatory-organisations-sros/sro-member-search/",
    "Notes": "Used to verify whether the entity is a member of a FINMA-recognised SRO for AML supervision purposes"
  },
  {
    "Country": "Switzerland",
    "Area of check": "SRO recognition verification",
    "Source type": "Regulatory information source",
    "Register / Portal": "List of FINMA-recognised Self-Regulatory Organisations",
    "Authority": "Swiss Financial Market Supervisory Authority / FINMA",
    "What to verify": "Whether the relevant SRO is recognised by FINMA and included in the official list of recognised self-regulatory organisations",
    "Search by": "SRO name",
    "Link": "https://www.finma.ch/en/authorisation/self-regulatory-organisations-sros/",
    "Notes": "Used to verify that the SRO named by the client is officially recognised by FINMA"
  },
  {
    "Country": "Switzerland",
    "Area of check": "Regulatory warning check",
    "Source type": "Warning list",
    "Register / Portal": "FINMA Warning List",
    "Authority": "Swiss Financial Market Supervisory Authority / FINMA",
    "What to verify": "Companies or individuals appearing on FINMA’s warning list, including potential unauthorised financial market activity",
    "Search by": "Company name / individual name / website",
    "Link": "https://www.finma.ch/en/finma-public/warnungen/warnliste",
    "Notes": "Used to identify FINMA warnings or regulatory concerns involving the company or related parties"
  },
  {
    "Country": "Switzerland",
    "Area of check": "Cybercrime / fraud warning check",
    "Source type": "Warning list",
    "Register / Portal": "Cybercrimepolice.ch Warning List",
    "Authority": "Cybercrimepolice.ch / Swiss police-related warning source",
    "What to verify": "Websites, companies or names associated with potential cybercrime, online fraud or scam-related warnings",
    "Search by": "Company name / website / domain",
    "Link": "https://cybercrimepolice.ch/de/warnliste",
    "Notes": "Used to identify potential cybercrime, fraud or scam-related warning indicators"
  },
  {
    "Country": "Switzerland",
    "Area of check": "International regulatory warning check",
    "Source type": "International warning database",
    "Register / Portal": "IOSCO I-SCAN",
    "Authority": "International Organization of Securities Commissions / IOSCO",
    "What to verify": "International warnings issued by securities and financial regulators regarding unauthorised firms or suspicious financial activity",
    "Search by": "Company name / website / keyword",
    "Link": "https://www.iosco.org/i-scan/",
    "Notes": "Used as an additional international regulatory warning check for financial or investment-related activity"
  },
  {
    "Country": "Canada",
    "Area of check": "Corporate verification",
    "Source type": "Public business register",
    "Register / Portal": "Canada Business Registry",
    "Authority": "Innovation, Science and Economic Development Canada / ISED",
    "What to verify": "Company name, business registration details, jurisdiction, status and available corporate profile information",
    "Search by": "Company name / business number / corporation number, where available",
    "Link": "https://ised-isde.canada.ca/cbr-rec/en/search",
    "Notes": "Used to verify official corporate registration data and cross-check information provided in the initial questionnaire"
  },
  {
    "Country": "Canada",
    "Area of check": "Federal corporation verification",
    "Source type": "Public register",
    "Register / Portal": "Search for a Federal Corporation",
    "Authority": "Corporations Canada / ISED",
    "What to verify": "Federal corporation name, corporation number, status, registered office address, incorporation date and available filing information",
    "Search by": "Company name / corporation number",
    "Link": "https://ised-isde.canada.ca/cc/lgcy/fdrlCrpSrch.html",
    "Notes": "Used to verify whether the entity is incorporated federally in Canada and to confirm federal corporate registration data"
  },
  {
    "Country": "Canada",
    "Area of check": "MSB / FMSB registration verification",
    "Source type": "Regulatory register",
    "Register / Portal": "FINTRAC MSB Registry",
    "Authority": "Financial Transactions and Reports Analysis Centre of Canada / FINTRAC",
    "What to verify": "MSB/FMSB registration status, registration number, company name, address, website, services offered, initial registration date, expiry date and revocation or cessation details, where applicable",
    "Search by": "Company name / registration number",
    "Link": "https://fintrac-canafe.canada.ca/msb-esm/reg-eng",
    "Notes": "Used to verify whether the entity is registered with FINTRAC as an MSB or FMSB and to confirm the scope of registered money services"
  },
  {
    "Country": "Canada",
    "Area of check": "PSP registration verification",
    "Source type": "Regulatory register",
    "Register / Portal": "Bank of Canada PSP Registry",
    "Authority": "Bank of Canada",
    "What to verify": "PSP registration status, registration number, company name, address, website, services offered, initial registration date, expiry date and cancellation or cessation details, where applicable",
    "Search by": "Company name / registration number",
    "Link": "https://www.bankofcanada.ca/core-functions/retail-payments-supervision/psp-registry/",
    "Notes": "Used to verify whether the entity is registered with the Bank of Canada as a payment service provider under the retail payments framework"
  },
  {
    "Country": "Canada",
    "Area of check": "Regulatory adverse media / FINTRAC mentions check",
    "Source type": "Regulatory website search",
    "Register / Portal": "FINTRAC website search / News and publications",
    "Authority": "FINTRAC / Government of Canada",
    "What to verify": "Mentions of the company in FINTRAC publications, news releases, notices, enforcement materials or other regulatory information",
    "Search by": "Company name / keywords",
    "Link": "https://www.canada.ca/en/financial-transactions-reports-analysis/search.html#",
    "Notes": "Used to identify adverse regulatory mentions or relevant FINTRAC publications involving the company"
  },
  {
    "Country": "Canada",
    "Area of check": "Sanctions screening",
    "Source type": "Sanctions list",
    "Register / Portal": "Consolidated Canadian Autonomous Sanctions List",
    "Authority": "Global Affairs Canada",
    "What to verify": "Sanctioned individuals and entities subject to Canadian autonomous sanctions, including identifying information and applicable sanctions measures",
    "Search by": "Company name / individual name / related party name",
    "Link": "https://www.international.gc.ca/world-monde/international_relations-relations_internationales/sanctions/consolidated-consolide.aspx?lang=eng",
    "Notes": "Used to screen the company, UBOs, directors, representatives and other related parties against Canadian sanctions lists"
  },
  {
    "Country": "Canada",
    "Area of check": "FINTRAC penalties check",
    "Source type": "Enforcement / penalties list",
    "Register / Portal": "FINTRAC Administrative Monetary Penalties",
    "Authority": "FINTRAC",
    "What to verify": "Administrative monetary penalties, non-compliance findings, penalty notices and enforcement actions involving reporting entities",
    "Search by": "Company name / keywords",
    "Link": "https://fintrac-canafe.canada.ca/pen/4-eng",
    "Notes": "Used to identify whether the company has been subject to FINTRAC administrative monetary penalties or enforcement actions"
  },
  {
    "Country": "Canada",
    "Area of check": "Apostille verification\nBritish Colimbia, Alberta, Saskatchewan",
    "Source type": "Apostille e-Register",
    "Register / Portal": "Government of Canada Apostille e-Register",
    "Authority": "Global Affairs Canada",
    "What to verify": "Official online register for verifying apostilles issued by Global Affairs Canada, British Columbia, Alberta and Saskatchewan. Verification is performed using the apostille number and date of issue.",
    "Search by": "Apostille number / Issue date",
    "Link": "https://apostille-gac.powerappsportals.com/en/eregister-eregistre/",
    "Notes": "Used to verify the authenticity and validity of apostilles issued by Global Affairs Canada, British Columbia, Alberta and Saskatchewan."
  },
  {
    "Country": "Canada",
    "Area of check": "Apostille verification\nOntario",
    "Source type": "Apostille validity check",
    "Register / Portal": "Ontario Apostille Validity Check",
    "Authority": "Official Documents Services (Ontario Ministry of Public and Business Service Delivery and Procurement)",
    "What to verify": "Official verification service for apostilles issued in the Province of Ontario. Verification is performed using the apostille number and date of issue.",
    "Search by": "Apostille number / Issue date",
    "Link": "https://www.officialdocuments.mgcs.gov.on.ca/en-US/validity-check/",
    "Notes": "Used to verify the authenticity and validity of apostilles issued by the Province of Ontario"
  },
  {
    "Country": "St. Vincent and the Grenadines",
    "Area of check": "Corporate verification",
    "Source type": "Public register",
    "Register / Portal": "FSA Entity Name Search",
    "Authority": "Financial Services Authority / FSA SVG",
    "What to verify": "Company name, registration number, business type, registered agent, legal form, status, registration date and available corporate registration details",
    "Search by": "Company name / registration number / business type / registered agent",
    "Link": "https://fsasvg.com/entity-name-search/",
    "Notes": "Used to verify official corporate registration data and confirm whether the entity appears in the FSA SVG entity database"
  },
  {
    "Country": "St. Vincent and the Grenadines",
    "Area of check": "Regulatory warning check",
    "Source type": "Warning list / investor alerts",
    "Register / Portal": "FSA Alerts",
    "Authority": "Financial Services Authority / FSA SVG",
    "What to verify": "Warning notices, unauthorised firms, unauthorised virtual asset service providers, public notices and other regulatory alerts",
    "Search by": "Company name / website / trading name / keywords",
    "Link": "https://fsasvg.com/tag/alerts/",
    "Notes": "Used to identify FSA warnings, unauthorised activity or other regulatory concerns involving the company"
  },
  {
    "Country": "St. Vincent and the Grenadines",
    "Area of check": "Watch list screening",
    "Source type": "Watch list",
    "Register / Portal": "FSA Watch Lists",
    "Authority": "Financial Services Authority / FSA SVG",
    "What to verify": "Individuals and entities with which Vincentian registered companies should not conduct business",
    "Search by": "Company name / individual name / related party name",
    "Link": "https://fsasvg.com/docs/watch-lists/",
    "Notes": "Used to identify persons or entities listed by FSA as restricted or high-risk counterparties"
  },
  {
    "Country": "St. Vincent and the Grenadines",
    "Area of check": "Sanctions / terrorist financing screening",
    "Source type": "Sanctions / terrorist watch list",
    "Register / Portal": "SVG FIU Terrorist Watch Lists",
    "Authority": "Financial Intelligence Unit / FIU SVG",
    "What to verify": "Individuals, entities and organisations listed under terrorist financing or targeted financial sanctions watch lists",
    "Search by": "Company name / individual name / related party name",
    "Link": "https://svgfiu.com/index.php/resources/terrorist-watch-lists",
    "Notes": "Used to screen the company, UBOs, directors, representatives and other related parties against FIU terrorist watch lists"
  },
  {
    "Country": "France",
    "Area of check": "Corporate verification",
    "Source type": "Official public register",
    "Register / Portal": "National Business Register / Registre national des entreprises (RNE)",
    "Authority": "INPI / French National Institute of Industrial Property",
    "What to verify": "Company name, SIREN/SIRET number, legal form, registered address, registration status, activity and available company documents",
    "Search by": "Company name / SIREN / SIRET",
    "Link": "https://registre.entreprises.gouv.fr/",
    "Notes": "Used to verify official corporate registration data in the French National Business Register"
  },
  {
    "Country": "France",
    "Area of check": "Corporate data verification",
    "Source type": "Official public database",
    "Register / Portal": "DATA INPI / Companies Database",
    "Authority": "INPI / French National Institute of Industrial Property",
    "What to verify": "Company name, SIREN number, registered office, legal form, directors or representatives where available, activity information and available RNE data",
    "Search by": "Company name / SIREN / director name / keywords",
    "Link": "https://data.inpi.fr/",
    "Notes": "Used as an official INPI source to cross-check corporate registration data and available company information"
  },
  {
    "Country": "France",
    "Area of check": "SIREN / SIRET verification",
    "Source type": "Official statistical register",
    "Register / Portal": "Avis de situation Sirene",
    "Authority": "INSEE",
    "What to verify": "SIREN/SIRET status, establishment details, company name, registered establishment address, APE/NAF activity code and active/closed status",
    "Search by": "SIREN / SIRET",
    "Link": "https://avis-situation-sirene.insee.fr/",
    "Notes": "Used to verify the company’s official SIREN/SIRET registration and establishment status"
  },
  {
    "Country": "France",
    "Area of check": "Kbis extract request",
    "Source type": "Paid commercial service",
    "Register / Portal": "Kbis.services",
    "Authority": "Kbis.services",
    "What to verify": "Kbis extract, company legal name, registration number, address, legal structure and representatives, based on available French commercial register data",
    "Search by": "Company name / SIREN / registration number",
    "Link": "https://en.kbis.services/",
    "Notes": "Optional paid source used to obtain a Kbis extract. Not recommended as the primary official verification source"
  },
  {
    "Country": "France",
    "Area of check": "Kbis / company documents request",
    "Source type": "Paid commercial service",
    "Register / Portal": "Portail Société Pro",
    "Authority": "Portail Société Pro",
    "What to verify": "Kbis or other company documents, where available through the service",
    "Search by": "Company name / SIREN / SIRET",
    "Link": "https://portail-societe-pro.com/",
    "Notes": "Optional paid commercial source only. Better not to use as a primary AML/KYC verification source"
  },
  {
    "Country": "Costa Rica",
    "Area of check": "Corporate verification",
    "Source type": "Public register",
    "Register / Portal": "Registro Nacional / RNP Digital",
    "Authority": "National Registry of Costa Rica / Registro Nacional",
    "What to verify": "Company name, legal entity registration data, legal status, registration details and available corporate certification information",
    "Search by": "Company name / legal entity number / identification number",
    "Link": "https://rnpdigital.com/",
    "Notes": "Used to verify official corporate registration data through the National Registry online services"
  },
  {
    "Country": "Costa Rica",
    "Area of check": "Legal entity verification",
    "Source type": "Public register",
    "Register / Portal": "Registro Nacional — Personas Jurídicas",
    "Authority": "National Registry of Costa Rica / Registro Nacional",
    "What to verify": "Legal entity registration data, company name, legal status, registered details and available information on legal persons",
    "Search by": "Company name / legal entity number",
    "Link": "https://www.rnpdigital.com/personas_juridicas/",
    "Notes": "Used to verify legal entity information. The page belongs to RNP, but it may require direct access due to technical/IP restrictions"
  },
  {
    "Country": "Costa Rica",
    "Area of check": "Financial institution supervision check",
    "Source type": "Regulatory register",
    "Register / Portal": "List of Entities Supervised by SUGEF",
    "Authority": "General Superintendence of Financial Entities / SUGEF",
    "What to verify": "Whether the entity is subject to SUGEF supervision, supervised entity name, category and available supervision-related information",
    "Search by": "Company name / entity name",
    "Link": "https://www.sugef.fi.cr/entidades_supervisadas/lista_entidades_supervisadas_por_SUGEF.aspx",
    "Notes": "Used to verify whether the entity is supervised by SUGEF as a financial entity"
  },
  {
    "Country": "Costa Rica",
    "Area of check": "Financial sector regulatory source",
    "Source type": "Regulatory authority website",
    "Register / Portal": "SUGEF official website",
    "Authority": "General Superintendence of Financial Entities / SUGEF",
    "What to verify": "Regulatory information, supervised entities, reports, APNFD information and other official SUGEF publications",
    "Search by": "Company name / keywords / regulatory category",
    "Link": "https://www.sugef.fi.cr/",
    "Notes": "Used as the main regulatory source for financial entities and AML-related SUGEF information"
  },
  {
    "Country": "Costa Rica",
    "Area of check": "APNFD / AML registration check",
    "Source type": "AML registration report",
    "Register / Portal": "SUGEF APNFDs Report / Sujetos Inscritos Art. 15 y Art. 15 bis",
    "Authority": "General Superintendence of Financial Entities / SUGEF",
    "What to verify": "Registration of designated non-financial businesses and professions under Law 7786, registration status and available entity details",
    "Search by": "Company name / identification number",
    "Link": "https://www.sugef.fi.cr/SIPO.Reportes/frmReporteAPNFDS_ART15.aspx",
    "Notes": "Used to check whether the entity is registered with SUGEF as an APNFD / DNFBP for AML/CFT purposes"
  },
  {
    "Country": "Costa Rica",
    "Area of check": "APNFD registration status check",
    "Source type": "AML registration status search",
    "Register / Portal": "Consulta Estado de Inscripción APNFDs",
    "Authority": "General Superintendence of Financial Entities / SUGEF",
    "What to verify": "APNFD registration status under Law 7786, status of inscription and available registration details",
    "Search by": "Company name / identification number",
    "Link": "https://www.sugef.fi.cr/sujetos%20inscritos%20ley%207786%20-%20(%20apnfds)/Consulta_Estado_Inscripcion_%20APNFDs.aspx",
    "Notes": "Used to verify the current APNFD registration status of the entity, where applicable"
  },
  {
    "Country": "Costa Rica",
    "Area of check": "Securities / investment warning check",
    "Source type": "Warning list / investor alerts",
    "Register / Portal": "SUGEVAL Investor Alerts",
    "Authority": "General Superintendence of Securities / SUGEVAL",
    "What to verify": "Investor alerts, unauthorised investment offers, securities-related warnings and entities not authorised to make public offers or provide securities intermediation",
    "Search by": "Company name / trading name / website / keywords",
    "Link": "https://www.sugeval.fi.cr/Informacion-inversionistas/alertas-al-inversionista",
    "Notes": "Used to identify securities, investment or unauthorised public offering warnings involving the company"
  },
  {
    "Country": "Costa Rica",
    "Area of check": "Sanctions / terrorist financing screening",
    "Source type": "Sanctions / FIU alerts",
    "Register / Portal": "ICD / UIF CSNU Alerts",
    "Authority": "Costa Rican Institute on Drugs / Financial Intelligence Unit",
    "What to verify": "UN Security Council consolidated list alerts, OFAC-related alerts and financial intelligence notices relevant to sanctions or terrorist financing",
    "Search by": "Company name / individual name / related party name",
    "Link": "https://www.icd.go.cr/portalicd/index.php/mnu-alertas-uif/alertas-csnu-uif",
    "Notes": "Used to screen the company, UBOs, directors, representatives and other related parties against sanctions and FIU alert sources"
  },
  {
    "Country": "Australia",
    "Area of check": "Corporate verification",
    "Source type": "Public register",
    "Register / Portal": "ASIC Company and Organisation Registers / ASIC Connect",
    "Authority": "Australian Securities and Investments Commission / ASIC",
    "What to verify": "Company name, ACN, ABN where available, registered business names, company status, registration details, lodged documents and available organisation information",
    "Search by": "Company name / ACN / ABN / business name",
    "Link": "https://connectonline.asic.gov.au/",
    "Notes": "Used to verify official corporate registration data and company status"
  },
  {
    "Country": "Australia",
    "Area of check": "Business number / tax registration verification",
    "Source type": "Public business register",
    "Register / Portal": "ABN Lookup / Australian Business Register",
    "Authority": "Australian Business Register / Australian Taxation Office",
    "What to verify": "ABN status, entity name, business type, GST status, public ABR details and historical trading names where available",
    "Search by": "ABN / ACN / business name",
    "Link": "https://abr.business.gov.au/",
    "Notes": "Used to verify ABN, business status, GST registration and public business details"
  },
  {
    "Country": "Australia",
    "Area of check": "Business name verification",
    "Source type": "Public register",
    "Register / Portal": "ASIC Business Names Register",
    "Authority": "ASIC",
    "What to verify": "Registered business name, business name holder and availability/status of business name",
    "Search by": "Business name / business name holder",
    "Link": "https://asic.gov.au/online-services/search-asic-registers/business-names-register/",
    "Notes": "Used to verify whether a trading name/business name is officially registered and who holds it"
  },
  {
    "Country": "Australia",
    "Area of check": "Financial services / credit licence verification",
    "Source type": "Regulatory register",
    "Register / Portal": "ASIC Professional Registers Search",
    "Authority": "ASIC",
    "What to verify": "AFS licensees, credit licensees, authorised representatives, auditors, liquidators and other persons or organisations registered/licensed with ASIC",
    "Search by": "Company name / individual name / licence number / ACN / ABN",
    "Link": "https://asic.gov.au/online-services/search-asic-registers/professional-registers-search/",
    "Notes": "Used to verify whether the entity or related person is licensed or registered with ASIC to provide regulated services"
  },
  {
    "Country": "Australia",
    "Area of check": "VASP / virtual asset registration verification",
    "Source type": "Regulatory register",
    "Register / Portal": "AUSTRAC VASP Register",
    "Authority": "AUSTRAC",
    "What to verify": "Registration as a virtual asset service provider, registration status and available entity details",
    "Search by": "Company name / ABN / ACN, where available",
    "Link": "https://online.apps.austrac.gov.au/vaspr",
    "Notes": "Used to verify whether the entity is registered with AUSTRAC as a virtual asset service provider"
  },
  {
    "Country": "Australia",
    "Area of check": "Banned / disqualified persons and organisations check",
    "Source type": "Regulatory adverse register",
    "Register / Portal": "ASIC Banned and Disqualified Registers",
    "Authority": "ASIC",
    "What to verify": "Persons or organisations banned or disqualified from managing corporations, providing financial services or engaging in credit activities",
    "Search by": "Individual name / organisation name",
    "Link": "https://asic.gov.au/online-services/search-asic-registers/banned-and-disqualified-registers/",
    "Notes": "Used to screen directors, UBOs, representatives and related entities for ASIC bans or disqualifications"
  },
  {
    "Country": "Australia",
    "Area of check": "Insolvency and deregistration check",
    "Source type": "Public notices register",
    "Register / Portal": "ASIC Published Notices / Insolvency Notices",
    "Authority": "ASIC",
    "What to verify": "Insolvency notices, external administration notices, winding-up applications and deregistration notices",
    "Search by": "Company name / ACN",
    "Link": "https://publishednotices.asic.gov.au/",
    "Notes": "Used to identify insolvency, external administration or deregistration-related risks involving the company"
  },
  {
    "Country": "Australia",
    "Area of check": "Security interests / encumbrance check",
    "Source type": "Public register",
    "Register / Portal": "Personal Property Securities Register / PPSR",
    "Authority": "Australian Financial Security Authority / AFSA",
    "What to verify": "Security interests over personal property, goods or company assets",
    "Search by": "Grantor details / ACN / ABN / serial number, depending on search type",
    "Link": "https://www.ppsr.gov.au/",
    "Notes": "Optional check used where asset encumbrance/security interest risk is relevant"
  },
  {
    "Country": "Australia",
    "Area of check": "Complaints / dispute history check",
    "Source type": "Complaints database",
    "Register / Portal": "AFCA Financial Firm Search / Published Decisions",
    "Authority": "Australian Financial Complaints Authority / AFCA",
    "What to verify": "AFCA membership, complaint contact details, published complaint decisions and dispute history",
    "Search by": "Company name / financial firm name / keywords",
    "Link": "https://my.afca.org.au/ff-search/",
    "Notes": "Used to identify financial complaints, dispute history and conduct-related risk indicators"
  },
  {
    "Country": "Australia",
    "Area of check": "Sanctions screening",
    "Source type": "Sanctions list",
    "Register / Portal": "DFAT Consolidated List",
    "Authority": "Department of Foreign Affairs and Trade / DFAT",
    "What to verify": "Sanctioned individuals and entities under Australian sanctions laws",
    "Search by": "Company name / individual name / related party name",
    "Link": "https://www.dfat.gov.au/international-relations/security/sanctions/consolidated-list",
    "Notes": "Used to screen the company, UBOs, directors, representatives and other related parties against Australian sanctions lists"
  },
  {
    "Country": "Australia",
    "Area of check": "Listed company verification / announcements check",
    "Source type": "Stock exchange announcements database",
    "Register / Portal": "ASX Announcements Search",
    "Authority": "Australian Securities Exchange / ASX",
    "What to verify": "Listed company announcements, price-sensitive announcements, name changes, delisting information and market disclosures",
    "Search by": "ASX code / company name",
    "Link": "https://www.asx.com.au/asx/v2/statistics/announcements.do",
    "Notes": "Optional check used where the entity is listed on ASX or claims to be part of a listed group"
  },
  {
    "Country": "Dominica",
    "Area of check": "Corporate verification",
    "Source type": "Public register / e-filing portal",
    "Register / Portal": "CIPO Online Business Registry / E-Filing",
    "Authority": "Companies and Intellectual Property Office / CIPO",
    "What to verify": "Company name, registration details, business name, company status and available corporate registration information",
    "Search by": "Company name / registration number / business name",
    "Link": "https://efiling.cipo.gov.dm/#/",
    "Notes": "Used to verify corporate registration data through the official CIPO online business registry"
  },
  {
    "Country": "Dominica",
    "Area of check": "Corporate registry verification",
    "Source type": "Public registry authority",
    "Register / Portal": "Companies and Intellectual Property Office / CIPO",
    "Authority": "CIPO / Government of Dominica",
    "What to verify": "Registration and records relating to companies, business names, international business companies and intellectual property",
    "Search by": "Company name / business name / registration number",
    "Link": "https://www.cipo.gov.dm/",
    "Notes": "Used as the official corporate registry source for the Commonwealth of Dominica"
  },
  {
    "Country": "Dominica",
    "Area of check": "Financial services licence / registration verification",
    "Source type": "Regulatory register",
    "Register / Portal": "FSU Registered Entities Search",
    "Authority": "Financial Services Unit / FSU",
    "What to verify": "Whether the entity is registered or regulated by the FSU, including financial services entities such as offshore banks, money services businesses, insurance companies, credit unions and other financial entities",
    "Search by": "Company name / entity name",
    "Link": "https://www.fsu.gov.dm/registered-entities/search-financial-entities",
    "Notes": "Used to verify whether the entity appears as a registered financial entity with the FSU"
  },
  {
    "Country": "Dominica",
    "Area of check": "Money services business registration verification",
    "Source type": "Regulatory information source",
    "Register / Portal": "FSU Money Services Business",
    "Authority": "Financial Services Unit / FSU",
    "What to verify": "Money services business activity, including money transmission, cheque cashing, currency exchange, money orders, travellers cheques and related regulated services",
    "Search by": "Company name / entity name",
    "Link": "https://www.fsu.gov.dm/services/money-services-business",
    "Notes": "Used where the entity claims to provide money services business activity in Dominica"
  },
  {
    "Country": "Dominica",
    "Area of check": "Offshore banking licence verification",
    "Source type": "Regulatory information source",
    "Register / Portal": "FSU Offshore Banking",
    "Authority": "Financial Services Unit / FSU",
    "What to verify": "Offshore banking registration/licensing information and related FSU forms or guidance",
    "Search by": "Company name / entity name",
    "Link": "https://www.fsu.gov.dm/services/offshore-banking",
    "Notes": "Used where the entity claims to provide offshore banking or bank-like services in Dominica"
  },
  {
    "Country": "Dominica",
    "Area of check": "Non-compliant institution check",
    "Source type": "Regulatory warning / non-compliance list",
    "Register / Portal": "FSU Non-Compliant Institutions Search",
    "Authority": "Financial Services Unit / FSU",
    "What to verify": "Non-compliant institutions, unauthorised or non-registered financial entities and regulatory concerns",
    "Search by": "Company name / entity name",
    "Link": "https://www.fsu.gov.dm/non-compliant-institutions",
    "Notes": "Used to identify whether the entity appears as non-compliant or not authorised by the FSU"
  },
  {
    "Country": "Dominica",
    "Area of check": "Court and adverse litigation check",
    "Source type": "Court judgments database",
    "Register / Portal": "Eastern Caribbean Supreme Court Judgments — Commonwealth of Dominica",
    "Authority": "Eastern Caribbean Supreme Court",
    "What to verify": "Published judgments, civil disputes, enforcement matters, fraud-related cases, insolvency-related litigation or other adverse litigation involving the company or related parties",
    "Search by": "Company name / individual name / keywords",
    "Link": "https://www.eccourts.org/judgments?type=commonwealth-of-dominica",
    "Notes": "Used to identify adverse litigation, disputes or reputational risks involving the company, UBOs, directors or representatives"
  },
  {
    "Country": "Spain",
    "Area of check": "UBO verification",
    "Source type": "Beneficial ownership register",
    "Register / Portal": "Registro Central de Titularidades Reales / RCTIR",
    "Authority": "Ministry of Justice",
    "What to verify": "Beneficial ownership information, current beneficial owners of Spanish legal entities, historical beneficial ownership data where available, and information on trusts or similar structures operating in Spain",
    "Search by": "Company name / NIF / registration details, where available",
    "Link": "https://app.bde.es/rbe_spa/home",
    "Notes": "Used to verify beneficial ownership information for Spanish legal entities. Access may be restricted to competent authorities, obliged entities or persons with legitimate interest"
  },
  {
    "Country": "Spain",
    "Area of check": "1",
    "Source type": "2",
    "Register / Portal": "3",
    "Authority": "4",
    "What to verify": "5",
    "Search by": "6",
    "Link": "7",
    "Notes": "8"
  }
];
window.REGISTRY_DATA_UPDATED_AT = "2026-08-01 01:11 UTC";
